config/routes.rb
Rails.application.routes.draw do

  get 'suppliers/index'

  get 'settings/index'

  get 'statistics/index'

  resources :suppliers, :procurement, :sales, :inventories, :accounting, :clients
  get 'welcome/index'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  root 'welcome#index', as: 'welcome'

end

app/controllers/accounting_controller.rb
class AccountingController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Selects locale according to user's selection & athenticates users
  before_action :set_locale

  protected

    def set_locale
      if cookies[:mymms_locale] && I18n.available_locales.include?(cookies[:mymms_locale].to_sym)
        lang = cookies[:mymms_locale].to_sym
      else
        begin
          country_code = request.location.country_code
          if country_code
            country_code = country_code.downcase.to_sym
            # Use simplified Chinese for China mainland, English for others
            #[:zh_CN, :ru, :kz, :ua, :by, :tj, :uz, :md, :az, :am, :kg, :tm].include?(country_code) ? l = :Zh_CN : l = :en
            [:zh_CN].include?(country_code) ? lang = :Zh_CN : lang = :en
          else
            lang = I18n.default_locale # use default locale if cannot retrieve this info
          end
        rescue
          lang = I18n.default_locale
        ensure
          cookies.permanent[:mymms_locale] = lang
        end
      end
      I18n.locale = lang
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/procurement_controller.rb
class ProcurementController < ApplicationController
  def index
  end

  def create 
  end

  def update
  end

  def show
  end

  def edit
  end

  def destroy 
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end

  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:mymms_locale] = l
    redirect_to request.referer || root_url
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:set_locale]
      redirect_to welcome_url(locale: params[:set_locale])
      #redirect_to welcome_path(locale: params[:set_locale])
    end
  end
end

app/helpers/accounting_helper.rb
module AccountingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/procurement_helper.rb
module ProcurementHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounting/index.html.erb
<h1>Accounting#index</h1>
<p>Find me in app/views/accounting/index.html.erb</p>

app/views/accounting/show.html.erb
<h1>Accounting#show</h1>
<p>Find me in app/views/accounting/show.html.erb</p>

app/views/clients/index.html.erb
<h1>Clients#index</h1>
<p>Find me in app/views/clients/index.html.erb</p>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

app/views/inventories/index.html.erb
<h1>Inventories#index</h1>
<p>Find me in app/views/inventories/index.html.erb</p>

app/views/inventories/show.html.erb
<h1>Inventories#show</h1>
<p>Find me in app/views/inventories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- if set true, it will conflict with the Bootstrap in-place editing
    See https://howilearnedrails.wordpress.com/2014/08/17/how-to-remove-turbolinks-from-rails-4/
    See also https://github.com/klenis/bootstrap-x-editable-rails/issues/8 -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Bootstrap navbar -->
  <%= render 'shared/navigation' %>

  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-12">
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: "alert alert-dismissible alert-#{name}" %>
        <% end -%>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/sales/index.html.erb
<h1>Sales#index</h1>
<p>Find me in app/views/sales/index.html.erb</p>

app/views/sales/show.html.erb
<h1>Sales#show</h1>
<p>Find me in app/views/sales/show.html.erb</p>

app/views/settings/index.html.erb
<h1>Settings#index</h1>
<p>Find me in app/views/settings/index.html.erb</p>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="navbar-header col-xs-8">
        <%= link_to 'MyMMS', welcome_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.suppliers'), suppliers_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.procurement'), procurement_index_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.sales'), sales_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.inventories'), inventories_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.accounting'), accounting_index_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.clients'), clients_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.statistics'), statistics_index_path, class: 'navbar-brand' %>
        <%= link_to t('layouts.application.settings'), settings_index_path, class: 'navbar-brand' %>
        <%# = link_to "Import", import_index_path, class: 'navbar-brand' %>
        <%# = link_to "Export", export_index_path, class: 'navbar-brand' %>
        <%# = link_to "Search", search_index_path, class: 'navbar-brand' %>
        <%# = link_to "Help", help_index_path, class: 'navbar-brand' %>
      </div>

      <!-- Locale selector: http://www.sitepoint.com/go-global-rails-i18n/ -->
      <div class="navbar-header col-xs-2">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('layouts.application.languages.lang') %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('layouts.application.languages.en'), change_locale_path(:en) %></li>
              <li><%= link_to t('layouts.application.languages.zh_CN'), change_locale_path(:zh_CN) %></li>
            </ul>
          </li>
        </ul>
      </div>

      <!-- System user sign in/out links -->
      <!--https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password -->
      <div class="col-xs-2">
        <%# if user_signed_in? %>
          Signed in as <%# = current_user.email %><br /> 
          <%# = link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'navbar-link' %> | 
          <%# = link_to "Reset password", edit_user_registration_path %>
        <%# else %>
          <%# = link_to "Sign up", new_user_registration_path, class: 'navbar-link' %> |
          <%# = link_to "Sign in", new_user_session_path, class: 'navbar-link' %>
        <%# end %>
      </div>
    </div>
  </div>
</nav>

app/views/statistics/index.html.erb
<h1>Statistics#index</h1>
<p>Find me in app/views/statistics/index.html.erb</p>

app/views/suppliers/index.html.erb
<h1>Suppliers#index</h1>
<p>Find me in app/views/suppliers/index.html.erb</p>

app/views/welcome/index.html.erb
<h2><%= t('.hello') %></h2>
<p>
  The time is now: <%= Time.now %>
</p>